version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=123456
      - DB_NAME=categories_db
      - DB_DIALECT=postgres
      - DB_PORT=5432
    ports:
      - '3000:3000'
    depends_on:
      - postgres-db
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  postgres-db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
